// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anakphxrtggismrssopo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuYWtwaHhydGdnaXNtcnNzb3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTY3OTAsImV4cCI6MjA3MjQzMjc5MH0.lh-XVbpegu39x4sAMX0CJLJkgasgcliYtd9yV_Hct6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});